name = "savaspincasino-com-gr"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=savaspincasino.com.gr"
HMAC_KEY = "9b417e911dc1092ad346abdd3ad290e09140994d8153c792166a1aae11b66221"
COOKIE_NAME = "sxz"
PLAY_PATH = "discover"
BUTTON_ID = "p086e0cd026cb6dfb10814620fb3707b0"
GATE_SALT = "76bf0af701555142"
